import type { Preview } from '@storybook/react-vite'
import { withThemeByDataAttribute } from '@storybook/addon-themes'

// All Figma tokens (generated by `npm run tokens`), then the hand-written base styles
// and typography presets. base.css also imports the tokens; importing both is harmless
// and makes it clear where each comes from.
import '../src/tokens/css/index.css'
import '../src/styles/base.css'

const preview: Preview = {
  decorators: [
    // Adds a Light/Dark switch to the toolbar. It sets data-theme="light|dark" on <html>,
    // which is the attribute the Dark mode tokens in foundations/colors.css listen to.
    withThemeByDataAttribute({
      themes: { light: 'light', dark: 'dark' },
      defaultTheme: 'light',
      attributeName: 'data-theme',
      parentSelector: 'html',
    }),
  ],

  parameters: {
    options: {
      storySort: {
        order: [
          'Foundations',
          ['Introduction', 'Colors', 'Typography', 'Spacing & Sizing', 'Radius, Borders & Effects', 'Component Tokens'],
          '*',
        ],
      },
    },

    // The page background comes from the --background token, so the theme switch drives it.
    backgrounds: { disable: true },

    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/i,
      },
    },

    a11y: {
      // 'todo' - show a11y violations in the test UI only
      // 'error' - fail CI on a11y violations
      // 'off' - skip a11y checks entirely
      test: 'todo',
    },
  },
}

export default preview
